<a href="https://colab.research.google.com/github/youcine/Diamond-Price-Prediction-with-Machine-Learning/blob/main/Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Evaluation Using Cross-Validation**

**RandomForest**

In [ ]:
scores = cross_val_score(rf, X_train, y_train, scoring ="neg_mean_squared_error",cv = 10)
rf_rmse_scores = np.sqrt(-scores)
rf_rmse_scores

array([534.66122229, 518.78824222, 538.17376348, 575.76413234,
       540.60925556, 526.21698848, 547.88769078, 556.9721835 ,
       543.11514972, 519.20602191])

In [ ]:
print("Scores: ", rf_rmse_scores)
print("Mean: ", rf_rmse_scores.mean())
print("Standard Deviation: ", rf_rmse_scores.std())

Scores:  [534.66122229 518.78824222 538.17376348 575.76413234 540.60925556
 526.21698848 547.88769078 556.9721835  543.11514972 519.20602191]
Mean:  540.1394650281374
Standard Deviation:  16.56309745583089


data 2

In [ ]:
scores = cross_val_score(rf, X2_train, y2_train, scoring ="neg_mean_squared_error",cv = 10)
rf_rmse_scores = np.sqrt(-scores)
rf_rmse_scores

In [ ]:
print("Scores: ", rf_rmse_scores)
print("Mean: ", rf_rmse_scores.mean())
print("Standard Deviation: ", rf_rmse_scores.std())

**LGBM**

In [ ]:
lgbm_scores = cross_val_score(lgbm, X_train, y_train, scoring ="neg_mean_squared_error",cv = 10)
lgbm_rmse_scores = np.sqrt(-lgbm_scores)
lgbm_rmse_scores

[LightGBM] [Info] Total Bins 1153
[LightGBM] [Info] Number of data points in the train set: 30268, number of used features: 15
[LightGBM] [Info] Start training from score 3841.133673
[LightGBM] [Info] Total Bins 1152
[LightGBM] [Info] Number of data points in the train set: 30268, number of used features: 15
[LightGBM] [Info] Start training from score 3837.728459
[LightGBM] [Info] Total Bins 1154
[LightGBM] [Info] Number of data points in the train set: 30269, number of used features: 15
[LightGBM] [Info] Start training from score 3828.899270
[LightGBM] [Info] Total Bins 1150
[LightGBM] [Info] Number of data points in the train set: 30269, number of used features: 15
[LightGBM] [Info] Start training from score 3847.572070
[LightGBM] [Info] Total Bins 1152
[LightGBM] [Info] Number of data points in the train set: 30269, number of used features: 15
[LightGBM] [Info] Start training from score 3838.970035
[LightGBM] [Info] Total Bins 1151
[LightGBM] [Info] Number of data points in the trai

array([503.75214836, 509.54810948, 535.34478399, 562.82951398,
       527.92864554, 510.59474809, 540.30374362, 540.75932918,
       544.66070147, 509.62348855])

In [ ]:
print("Scores: ", lgbm_rmse_scores)
print("Mean: ", lgbm_rmse_scores.mean())
print("Standard Deviation: ", lgbm_rmse_scores.std())

Scores:  [503.75214836 509.54810948 535.34478399 562.82951398 527.92864554
 510.59474809 540.30374362 540.75932918 544.66070147 509.62348855]
Mean:  528.5345212278113
Standard Deviation:  18.506809449666974


data 2

In [ ]:
lgbm_scores = cross_val_score(lgbm, X2_train, y2_train, scoring ="neg_mean_squared_error",cv = 10)
lgbm_rmse_scores = np.sqrt(-lgbm_scores)
lgbm_rmse_scores

In [ ]:
print("Scores: ", lgbm_rmse_scores)
print("Mean: ", lgbm_rmse_scores.mean())
print("Standard Deviation: ", lgbm_rmse_scores.std())

**XGBoost**

In [ ]:
xgbm_scores = cross_val_score(xgbm, X_train, y_train, scoring ="neg_mean_squared_error",cv = 10)
xgbm_rmse_scores = np.sqrt(-xgbm_scores)
xgbm_rmse_scores

array([521.56642344, 507.24301766, 550.68265867, 560.23980338,
       521.35963595, 535.49976916, 545.19792576, 538.72292831,
       541.32104799, 505.70274578])

In [ ]:
print("Scores: ", xgbm_rmse_scores)
print("Mean: ", xgbm_rmse_scores.mean())
print("Standard Deviation: ", xgbm_rmse_scores.std())

Scores:  [521.56642344 507.24301766 550.68265867 560.23980338 521.35963595
 535.49976916 545.19792576 538.72292831 541.32104799 505.70274578]
Mean:  532.7535956079824
Standard Deviation:  17.27973702596814


data 2

In [ ]:
xgbm_scores = cross_val_score(xgbm, X2_train, y2_train, scoring ="neg_mean_squared_error",cv = 10)
xgbm_rmse_scores = np.sqrt(-xgbm_scores)
xgbm_rmse_scores

In [ ]:
print("Scores: ", xgbm_rmse_scores)
print("Mean: ", xgbm_rmse_scores.mean())
print("Standard Deviation: ", xgbm_rmse_scores.std())